env: production

storage:
  type: internal
  managed_pvc: true
  secrets:
    user: postgres
    password: password
app:
  image: gcr.io/nectar-bazaar/hub:latest
  image_pull_pol: Always
  service_type: ClusterIP
  secrets:
    key_base: whatever
frontend:
  ipp: Always
  image: gcr.io/nectar-bazaar/hub-front:latest