env: default

storage:
  type: internal
  managed_pvc: true
  secrets:
    user: user
    password: password
app:
  image: hub
  image_pull_pol: IfNotPresent
  service_type: ClusterIP
  secrets:
    key_base: