images:
  - "gcr.io/nectar-bazaar/wiz-ci-tami:latest"

steps:
  - id: "Build tami for the Wiz CI"
    waitFor: []
    name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "wiz-ci/kerbi"
      - "-t"
      - "gcr.io/nectar-bazaar/wiz-ci-tami:latest"
