kind: Operation
key: installation
title: Installation
prerequisites: []
stages:
  - key: assigns_stage
    kind: Stage
    title: Simple Assignments
    info: "Chart and state assignments that end with a manifest-apply."
    steps:
      - key: deploy_step
        title: "Deployment"
        kind: Step
        info: "Configures simple dep without applying."
        fields:
          - key: deployment.flavor
            kind: Field
            title: "Ice cream flavor"
            info: "The flavor shown on the website."
            type: select
            options:
              - key: vanilla
                value: Vanilla
              - key: chocolate
                value: Chocolate
          - key: deployment.replicas
            kind: Field
            title: "Replicas"
            info: "Initial pod replicas for the website"
            type: slider
            options:
              min: 1
              max: 15
              step: 1
      - key: svc_step
        title: "Service"
        kind: Step
        info: "Commits simple config and applies the manifest"
        resource_apply_filter:
          - "Deployment:*"
          - "Service:*"
        fields:
          - key: service.port
            kind: Field
            title: Service Port
            info: "Port for service to be accessible at"
            type: text-input
          - key: service.type
            kind: Field
            title: Service Port
            info: "Kubernetes network service type"
            type: select
            options:
              - key: "ClusterIP"
                value: "ClusterIP - accessible only inside the cluster"
              - key: "LoadBalancer"
                value: "LoadBalancer - accessible on the public internet"