
apiVersion: v1
kind: Pod
metadata:
  name: interp
  namespace: moz
  labels:
    app: interp
spec:
#  serviceAccountName: X
  containers:
    - name: interp
      image: interp
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 10; done;" ]
      env:
        - name: NECTAR_VALUES_PATH
          value: /etc/config/master
      volumeMounts:
        - name: configmap-volume
          mountPath: /etc/config
  volumes:
    - name: configmap-volume
      configMap:
        name: master
