release: 0.0.0
namespace: default
deployment:
  name: ice-cream
  image: gcr.io/nectar-bazaar/ice-cream-app:1.0.0
  replicas: 1
  flavor: vanilla
service:
  name: ice-cream
  port: 8080
  type: ClusterIP