apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - name: main
    port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.pod.name }}

---

apiVersion: v1
kind: Pod
metadata:
  namespace: {{ .Release.Name }}
  name: {{ .Values.pod.name }}
  labels:
    app: {{ .Values.pod.name }}
spec:
  containers:
  - name: main
    image: {{ .Values.pod.image }}
    imagePullPolicy: Always