
apiVersion: v1
kind: Pod
metadata:
  name: interpolator
  labels:
    app: interpolator
spec:
#  serviceAccountName: X
  containers:
    - name: interpolator
      image: interpolator
      imagePullPolicy: Never
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 10; done;" ]
  volumes:
    - name: main
      emptyDir: {}
