kind: Operation
id: installation
title: Installation
prerequisites: []
stages:
  - id: assigns_stage
    title: Simple Assignments
    info: "Chart and state assignments that end with a manifest-apply."
    steps:
      - id: deploy_step
        title: "Deployment"
        info: "Configures simple dep without applying."
        fields:
          - deployment.flavor
          - deployment.replicas

      - id: svc_step
        title: "Service"
        info: "Commits simple config and applies the manifest"
        action: StepApplyResAction
        fields:
          - service.port
          - service.type