kind: Operation
id: installation
title: Installation
prerequisites: []
stages:
  - nectar.operations.telem.stage-1
  - id: installation.flavor
    title: Simple Assignments
    info: "Chart and state assignments that end with a manifest-apply."
    steps:
      - id: deploy_step
        title: "Deployment"
        info: "Configures simple dep without applying."
        fields:
          - variable: deployment.flavor
          - variable: deployment.replicas
      - id: installation.networking
        title: "Service"
        info: "Commits simple config and applies the manifest"
        action: StepApplyResAction
        fields:
          - variable: service.port
          - variable: service.type