kind: Operation
id: installation
title: Installation
preflight_predicates: 
  - nectar.predicate.all-nodes-linux
  - nectar.predicate.all-node-containers-docker
  - nectar.predicate.metrics-server-running
  - nectar.predicate.calico-pods-present-for-netpol
stages:
  - nectar.stages.telem-storage
  - id: installation.flavor
    title: Simple Assignments
    info: "Chart and state assignments that end with a manifest-apply."
    steps:
      - id: deploy_step
        title: "Deployment"
        info: "Configures simple dep without applying."
        fields:
          - variable: deployment.flavor
          - variable: deployment.replicas
      - id: installation.networking
        title: "Service"
        info: "Commits simple config and applies the manifest"
        action: ApplyManifestAction
        fields:
          - variable: service.port
          - variable: service.type