kind: MockUpdate
id: vendor.mock-updates.not-next
inherit: vendor.mock-updates.partial
injections:
  frontend.image: 1.0.1

---

kind: MockUpdate
id: vendor.mock-updates.next
version: 2.0.0
inherit: vendor.mock-updates.release

---

kind: MockUpdate
inherit: vendor.mock-updates.wiz-update
id: vendor.mock-updates.next3
version: 2.0.0
wiz_type: dev-server
wiz_uri: http://localhost:5000
