kind: ManifestVariable
id: deployment.replicas
title: Website Pod Replicas
mode: public
tags: ['deployment', 'app']
info: "Amount of pod replicas for the website. More means
more resilience to traffic spikes and application failures."
input:
  kind: SliderInput
  min: 1
  max: 15
  step: 1
validation:
  - kind: FormatPredicate
    check_against: integer
  - operator: ">="
    check_against: 0
    tone: warning
    reason: Zero replicas will shut down the server
  - operator: "<"
    check_against: 10
    tone: warning
    reason: Demo app won't need this level of resillience

---

kind: ManifestVariable
id: deployment.flavor
title: Website Flavor
mode: public
tags: ['deployment', 'app']
info: "Ice-cream speciality for the website. Cannnot break the application
because of faulty value."
input:
  kind: SelectInput
  options:
    vanilla: Vanilla
    chocolate: Chocolate
validation:
  - operator: in
    check_against: [vanilla, chocolate]

---

kind: ManifestVariable
id: service.type
title: Service Type
tags: ['network', 'app']
info: "Kubernetes network service type"
input:
  kind: SelectInput
  options:
    ClusterIP: ClusterIP - accessible only inside the cluster
    LoadBalancer: LoadBalancer - accessible on the public internet
mode: public

---

kind: ManifestVariable
mode: public
id: service.port
title: Service Port
tags: ['network', 'app']
info: "Port for service to be accessible at"
validation:
  - kind: FormatPredicate
    check_against: integer

---

kind: ManifestVariable
mode: internal
id: deployment.image
tags: ['deployment', 'app']
title: Main application image
info: "Versioned application image. Should never be changed manually."
validation:
  - check_against: "gcr.io/nectar-bazaar/ice-cream-app:"
    operator: contains
    reason: Base image should never be different
